version: '3.7'

services:

  timer:
    image: wlewis95/jarrod-timer:first
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        max_attempts: 100
        window: 1h

